source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash', require: 'sinatra/flash'
gem 'bcrypt-ruby'

gem 'warden'
gem 'shotgun'
gem 'rack'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-timestamps'
gem 'dm-transactions'
gem 'dm-types'
gem 'dm-validations'
gem 'chef'